### ISSUE TITLE
Repository Not found - Installation Not possible

### ISSUE THREAD

**Issue by bryce2071** [wiltodelta/homeassistant-sugartv-card#1]
Hi

i tried to integrate IT to my ha, but wont Work.

Repository https://github.com/wiltodelta/homeassistant-sugartv-card not found

Do you have an Idea what could bei wrong?

Thx für your Work
Gr.pit

**Comment by wiltodelta** [comment]
It may have to do with the fact that I haven't been added to HACS yet -- I'll check.

But you can install using this method, as I did https://github.com/wiltodelta/homeassistant-sugartv-card#installing-via-hacs.

**Comment by wiltodelta** [comment]
@bryce2071 did it help?
