### ISSUE TITLE
Round up value

### ISSUE THREAD

**Issue by marc3k18** [wiltodelta/homeassistant-sugartv-card#2]
Hello,

We use mmol/L in Canada. Not certain if that the cause.

Thanks!

![PXL_20240107_071917300](https://github.com/wiltodelta/homeassistant-sugartv-card/assets/97817024/3c796059-0a5c-49c5-8204-6342f93ab5f8)

**Comment by wiltodelta** [comment]
@marc3k18 thank you! Will update soon!
